### ISSUE TITLE
Latest beta release throws exception on missing assembly when running under Cake.Tool

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Issues.Recipe#136]
I was testing the latest pushed beta release of Cake.Issues.Recipe (`0.4.0-beta0001`) that have been pushed to nuget.org.
When trying to run the scripts with `Cake.Tool` I am seeing an exception with the message:

```
Exception while resolving assembly System.Text.Encodings.Web: Could not load file or assembly 'System.Text.Encodings.Web, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

This only happens when running with `Cake.Tool`, using .NET Full Framework through `Cake` works as expected.

Link to build: https://ci.appveyor.com/project/AdmiringWorm/cake-recipe-tests/builds/34474307/job/ek9jscvagod22ow8#L1998
The full stacktrace can be seen below:

<details>
<summary>Exception StackTrace</summary>

```
Error: System.AggregateException: One or more errors occurred. (Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.) ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
   at Gazorator.Scripting.RazorScriptHostBase..ctor(TextWriter output, DynamicViewBag viewBag)
   at Gazorator.Scripting.RazorScriptHost`1..ctor(TModel model, TextWriter output, DynamicViewBag viewBag)
   at Gazorator.Scripting.RazorContentGenerator`1.GetGlobalsObject()
   at Gazorator.Scripting.RazorContentGeneratorBase.Generate(String csharpScript)
   at Gazorator.Gazorator.ProcessTemplateAsync(String template)
   at Cake.Issues.Reporting.Generic.GenericIssueReportGenerator.InternalCreateReport(IEnumerable`1 issues)
   at Submission#0.CreateIssueReport(IEnumerable`1 issues, IIssueReportFormat reportFormat, DirectoryPath repositoryRoot, FilePath outputFilePath) in :line 3690
   at Submission#0.<<Initialize>>b__0_3(IssuesData data) in C:\projects\cake-recipe-tests\src\tools\Cake.Issues.Recipe.0.4.0-beta0001\Content\build.cake:line 121
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass32_0.<Does>b__0(ICakeContext x) in C:\projects\cake\src\Cake.Core\CakeTaskBuilder.Execution.cs:line 82
   at Cake.Core.CakeTask.Execute(ICakeContext context) in C:\projects\cake\src\Cake.Core\CakeTask.cs:line 125
   at Cake.Core.DefaultExecutionStrategy.ExecuteAsync(CakeTask task, ICakeContext context) in C:\projects\cake\src\Cake.Core\DefaultExecutionStrategy.cs:line 87
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 336
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 359
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 369
   at Cake.Core.CakeEngine.RunTask(ICakeContext context, IExecutionStrategy strategy, CakeTask task, String target, Stopwatch stopWatch, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 284
   at Cake.Core.CakeEngine.RunTargetAsync(ICakeContext context, IExecutionStrategy strategy, ExecutionSettings settings) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 247
   at Cake.Scripting.BuildScriptHost.RunTargetAsync(String target) in C:\projects\cake\src\Cake\Scripting\BuildScriptHost.cs:line 47
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target) in C:\projects\cake\src\Cake.Core\Scripting\ScriptHost.cs:line 191
   at Submission#0.<get_Build>b__691_0(String target) in C:\projects\cake-recipe-tests\src\tools\Cake.Recipe.2.0.0-alpha0341\Content\build.cake:line 457
   at Submission#0.Builder.RunDotNetCore() in C:\projects\cake-recipe-tests\src\tools\Cake.Recipe.2.0.0-alpha0341\Content\build.cake:line 487
   at Submission#0.<<Initialize>>d__0.MoveNext() in C:\projects\cake-recipe-tests\src\NetCore.cake:line 51
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script) in C:\projects\cake\src\Cake\Scripting\Roslyn\RoslynScriptSession.cs:line 136
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 219
   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line 41
   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 74
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Text.Encodings.Web, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Gazorator.Scripting.RazorScriptHostBase..ctor(TextWriter output, DynamicViewBag viewBag)
   at Gazorator.Scripting.RazorScriptHost`1..ctor(TModel model, TextWriter output, DynamicViewBag viewBag)
   at Gazorator.Scripting.RazorContentGenerator`1.GetGlobalsObject()
   at Gazorator.Scripting.RazorContentGeneratorBase.Generate(String csharpScript)
   at Gazorator.Gazorator.ProcessTemplateAsync(String template)
   at Cake.Issues.Reporting.Generic.GenericIssueReportGenerator.InternalCreateReport(IEnumerable`1 issues)
   at Submission#0.CreateIssueReport(IEnumerable`1 issues, IIssueReportFormat reportFormat, DirectoryPath repositoryRoot, FilePath outputFilePath) in :line 3690
   at Submission#0.<<Initialize>>b__0_3(IssuesData data) in C:\projects\cake-recipe-tests\src\tools\Cake.Issues.Recipe.0.4.0-beta0001\Content\build.cake:line 121
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass32_0.<Does>b__0(ICakeContext x) in C:\projects\cake\src\Cake.Core\CakeTaskBuilder.Execution.cs:line 82
   at Cake.Core.CakeTask.Execute(ICakeContext context) in C:\projects\cake\src\Cake.Core\CakeTask.cs:line 125
   at Cake.Core.DefaultExecutionStrategy.ExecuteAsync(CakeTask task, ICakeContext context) in C:\projects\cake\src\Cake.Core\DefaultExecutionStrategy.cs:line 87
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 336
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 359
   at Cake.Core.CakeEngine.ExecuteTaskAsync(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 369
   at Cake.Core.CakeEngine.RunTask(ICakeContext context, IExecutionStrategy strategy, CakeTask task, String target, Stopwatch stopWatch, CakeReport report) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 284
   at Cake.Core.CakeEngine.RunTargetAsync(ICakeContext context, IExecutionStrategy strategy, ExecutionSettings settings) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 247
   at Cake.Scripting.BuildScriptHost.RunTargetAsync(String target) in C:\projects\cake\src\Cake\Scripting\BuildScriptHost.cs:line 47
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target) in C:\projects\cake\src\Cake.Core\Scripting\ScriptHost.cs:line 191
   at Submission#0.<get_Build>b__691_0(String target) in C:\projects\cake-recipe-tests\src\tools\Cake.Recipe.2.0.0-alpha0341\Content\build.cake:line 457
   at Submission#0.Builder.RunDotNetCore() in C:\projects\cake-recipe-tests\src\tools\Cake.Recipe.2.0.0-alpha0341\Content\build.cake:line 487
   at Submission#0.<<Initialize>>d__0.MoveNext() in C:\projects\cake-recipe-tests\src\NetCore.cake:line 51
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunSubmissionsAsync(ScriptExecutionState executionState, ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

</details>

**Comment by pascalberger** [comment]
I assume this is somehow related to the AppVeyor build image, since I've integration tests running on Windows with .NET Core tool which work fine (see [here](https://dev.azure.com/cake-contrib/Cake.Issues.Recipe/_build/results?buildId=4095&view=logs&j=98133c42-4eea-5460-6d27-e44d50f8052d)).

**Comment by pascalberger** [comment]
I see that you're using `Visual Studio 2015` image in the failing build. Can you try with `Visual Studio 2019` image?

**Comment by AdmiringWorm** [comment]
@pascalberger Yeah, I am waiting on the VS2019 image to complete the run (currently VS2015 and VS2017 is failing).

Also have failing build on travis as well, but that looks like a different issue.

**Comment by AdmiringWorm** [comment]
Same problem on the `Visual Studio 2019` image: https://ci.appveyor.com/project/AdmiringWorm/cake-recipe-tests/builds/34474307/job/adq9eoex7wafkb92#L2021

**Comment by pascalberger** [comment]
Interesting. Then the question is what is the difference between the Azure Pipelines and AppVeyor images.
